package vue;

public enum Pays {
    AFGHANISTAN("Afghanistan"),
    AFRIQUE_DU_SUD("Afrique du Sud"),
    ALBANIE("Albanie"),
    ALGERIE("Algérie"),
    ANDORRE("Andorre"),
    ANGOLA("Angola"),
    ANTIGUA_ET_BARBUDA("Antigua-et-Barbuda"),
    ARABIE_SAOUDITE("Arabie saoudite"),
    ARGENTINE("Argentine"),
    ARMENIE("Arménie"),
    AUSTRALIE("Australie"),
    AUTRICHE("Autriche"),
    AZERBAIDJAN("Azerbaïdjan"),
    BAHAMAS("Bahamas"),
    BAHREIN("Bahreïn"),
    BANGLADESH("Bangladesh"),
    BARBADE("Barbade"),
    BIELORUSSIE("Biélorussie"),
    BELGIQUE("Belgique"),
    BELIZE("Belize"),
    BENIN("Bénin"),
    BHOUTAN("Bhoutan"),
    BOLIVIE("Bolivie"),
    BOSNIE_HERZEGOVINE("Bosnie-Herzégovine"),
    BOTSWANA("Botswana"),
    BRESIL("Brésil"),
    BRUNEI("Brunei"),
    BULGARIE("Bulgarie"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODGE("Cambodge"),
    CAMEROUN("Cameroun"),
    CANADA("Canada"),
    CAP_VERT("Cap-Vert"),
    CHILI("Chili"),
    CHINE("Chine"),
    CHYPRE("Chypre"),
    COLOMBIE("Colombie"),
    COMORES("Comores"),
    CONGO_BRAZZAVILLE("Congo-Brazzaville"),
    CONGO_KINSHASA("Congo-Kinshasa"),
    COREE_DU_NORD("Corée du Nord"),
    COREE_DU_SUD("Corée du Sud"),
    COSTA_RICA("Costa Rica"),
    COTE_D_IVOIRE("Côte d'Ivoire"),
    CROATIE("Croatie"),
    CUBA("Cuba"),
    DANNERMARK("Danemark"),
    DJIBOUTI("Djibouti"),
    DOMINIQUE("Dominique"),
    EGYPTE("Égypte"),
    EMIRATES_ARABES_UNIS("Émirats arabes unis"),
    EQUATEUR("Équateur"),
    ERYTHREE("Érythrée"),
    ESTONIE("Estonie"),
    ESWATINI("Eswatini"),
    ETHIOPIE("Éthiopie"),
    FEDERATION_DE_RUSSIE("Fédération de Russie"),
    FIDJI("Fidji"),
    FINLANDE("Finlande"),
    FRANCE("France"),
    GABON("Gabon"),
    GAMBIE("Gambie"),
    GEORGIE("Géorgie"),
    GHANA("Ghana"),
    GRECE("Grèce"),
    GRENADA("Grenade"),
    GUATEMALA("Guatemala"),
    GUINEE("Guinée"),
    GUINEE_BISSAU("Guinée-Bissau"),
    GUINEE_EQUATORIALE("Guinée équatoriale"),
    GUYANA("Guyana"),
    HAITI("Haïti"),
    HONDURAS("Honduras"),
    HONGRIE("Hongrie"),
    INDE("Inde"),
    INDONESIE("Indonésie"),
    IRAN("Iran"),
    IRAK("Irak"),
    IRLANDE("Irlande"),
    ISLANDE("Islande"),
    ISRAEL("Israël"),
    ITALIE("Italie"),
    JAMAIQUE("Jamaïque"),
    JAPON("Japon"),
    JORDANIE("Jordanie"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRGHIZSTAN("Kirghizistan"),
    KIRIBATI("Kiribati"),
    KOWEIT("Koweit"),
    LAOS("Laos"),
    LESOTHO("Lesotho"),
    LETTONIE("Lettonie"),
    LIBAN("Liban"),
    LIBERIA("Libéria"),
    LIBYE("Libye"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIE("Lituanie"),
    LUXEMBOURG("Luxembourg"),
    MACEDOINE_DU_NORD("Macédoine du Nord"),
    MADAGASCAR("Madagascar"),
    MALAISIE("Malaisie"),
    MALAVI("Malawi"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTE("Malte"),
    MAROC("Maroc"),
    MARSHALL("Marshall"),
    MAURICE("Maurice"),
    MAURITANIE("Mauritanie"),
    MEXIQUE("Mexique"),
    MICRONESIE("Micronésie"),
    MOLDAVIE("Moldavie"),
    MONACO("Monaco"),
    MONGOLIE("Mongolie"),
    MONTENEGRO("Monténégro"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIE("Namibie"),
    NAURU("Nauru"),
    NEPAL("Népal"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORVEGE("Norvège"),
    NOUVELLE_ZELANDE("Nouvelle-Zélande"),
    OMAN("Oman"),
    OUGANDA("Ouganda"),
    OUZBÉKISTAN("Ouzbékistan"),
    PAKISTAN("Pakistan"),
    PALAOS("Palaos"),
    PANAMA("Panama"),
    PAPOUASIE_NOUVELLE_GUINEE("Papouasie-Nouvelle-Guinée"),
    PARAGUAY("Paraguay"),
    PAYS_BAS("Pays-Bas"),
    PEROU("Pérou"),
    PHILIPPINES("Philippines"),
    POLOGNE("Pologne"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    REPUBLIQUE_CENTRAFRICAINE("République centrafricaine"),
    REPUBLIQUE_DEMOCRATIQUE_DU_CONGO("République démocratique du Congo"),
    REPUBLIQUE_DOMINICAINE("République dominicaine"),
    REPUBLIQUE_TCHEQUE("République tchèque"),
    REPUBLIQUE_DU_CONGO("République du Congo"),
    REPUBLIQUE_KIRGHIZE("République kirghize"),
    REPUBLIQUE_DE_COREE("République de Corée"),
    REPUBLIQUE_DE_MAURICE("République de Maurice"),
    REPUBLIQUE_DU_SUDAN_DU_SUD("République du Soudan du Sud"),
    REPUBLIQUE_SLOVAQUE("République slovaque"),
    REPUBLIQUE_DE_ZAMBIE("République de Zambie"),
    REPUBLIQUE_UNIE_DE_TANZANIE("République-Unie de Tanzanie"),
    ROUMANIE("Roumanie"),
    RWANDA("Rwanda"),
    SAINT_CHRISTOPHE_ET_NIEVES("Saint-Christophe-et-Niévès"),
    SAINT_KITTS_ET_NEVIS("Saint-Kitts-et-Nevis"),
    SAINT_MARIN("Saint-Marin"),
    SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines"),
    SAINT_SIEGE("Saint-Siège"),
    SALOMON("Salomon"),
    SAMOA("Samoa"),
    SAO_TOME_ET_PRINCIPE("Sao Tomé-et-Principe"),
    SENEGAL("Sénégal"),
    SERBIE("Serbie"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPOUR("Singapour"),
    SLOVAQUIE("Slovaquie"),
    SLOVENIE("Slovénie"),
    SOMALIA("Somalie"),
    SODAN("Soudan"),
    SRI_LANKA("Sri Lanka"),
    SUEDE("Suède"),
    SUISSE("Suisse"),
    SURINAME("Suriname"),
    SWAZILAND("Swaziland"),
    SYRIE("Syrie"),
    TADJIKISTAN("Tadjikistan"),
    TANZANIE("Tanzanie"),
    TCHAD("Tchad"),
    THAILANDE("Thaïlande"),
    TIMOR_ORIENTAL("Timor oriental"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINITE_ET_TOBAGO("Trinité-et-Tobago"),
    TUNISIE("Tunisie"),
    TURKMENISTAN("Turkménistan"),
    TURQUIE("Turquie"),
    TUVALU("Tuvalu"),
    UKRAINE("Ukraine"),
    URUGUAY("Uruguay"),
    VANUATU("Vanuatu"),
    VATICAN("Vatican"),
    VENEZUELA("Venezuela"),
    VIETNAM("Viêt Nam"),
    YEMEN("Yémen"),
    ZAMBIE("Zambie"),
    ZIMBABWE("Zimbabwe");
    
    private final String nom;

    private Pays(String nom) {
        this.nom = nom;
    }

    public String getNom() {
        return nom;
    }
}
