package Lancement;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import DAO.ConnexionDB;

public class DataBase {

	/**
	 * Point d'entrée principal du programme. Appelle la méthode pour construire les tables de la base de données.
	 *
	 * @param args Les arguments de la ligne de commande (non utilisés dans cette application).
	 */
	public static void main(String[] args) {
		try {
			buildTables();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Obtient une connexion à la base de données avec la validation automatique désactivée.
	 *
	 * @return Une instance de {@code Connection} représentant la connexion à la base de données.
	 * @throws SQLException En cas d'erreur lors de l'obtention de la connexion.
	 */
	public static Connection getConnection() throws SQLException {
		ConnexionDB.getConnexionDB().setAutoCommit(false);
		return ConnexionDB.getConnexionDB().getConnexion();
	}

	/**
	 * Supprime la table spécifiée si elle existe dans la base de données.
	 *
	 * @param c         La connexion à la base de données.
	 * @param tableName Le nom de la table à supprimer.
	 * @throws SQLException En cas d'erreur lors de la suppression de la table.
	 */
	private static void dropTableIfExists(Connection c, String tableName) throws SQLException {
		Statement statement = c.createStatement();
		ResultSet tableExists = c.getMetaData().getTables(null, null, tableName.toUpperCase(), null);
		if (tableExists.next()) {
			statement.executeUpdate("DROP TABLE " + tableName);
		}
	}

	/**
	 * Construit les tables nécessaires dans la base de données.
	 * Et ajoute un jeu de données.
	 *
	 * @throws SQLException En cas d'erreur lors de la construction des tables.
	 */
	public static void buildTables() throws SQLException {
		Connection c = getConnection();
		Statement statement = c.createStatement();

		dropTableIfExists(c, "Participer");
		dropTableIfExists(c, "Arbitrer");
		dropTableIfExists(c, "Matchs");
		dropTableIfExists(c, "Tournoi");
		dropTableIfExists(c, "Joueur");
		dropTableIfExists(c, "Administrateur");
		dropTableIfExists(c, "Arbitres");
		dropTableIfExists(c, "Saison");
		dropTableIfExists(c, "Equipe");

		// Table Administrateur
		statement.executeUpdate("create table Administrateur (IdAdministrateur int GENERATED BY DEFAULT AS IDENTITY,"
				+ " Login Varchar(20), MotDePasse Varchar(50),"
				+ " constraint PK_IDADMINISTRATEUR PRIMARY KEY (idAdministrateur))");
		// Table Equipe
		statement.executeUpdate("CREATE TABLE Equipe (" + "NomEquipe varchar(50)," + "Pays varchar(100),"
				+ "CONSTRAINT PK_IDEQUIPE PRIMARY KEY (NomEquipe))");
		// Table Joueur
		statement.executeUpdate("CREATE TABLE Joueur (IdJoueur INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "Pseudo varchar(20) unique,"
				+ "NomEquipe varchar(50), constraint FK_JOUEUR_IDEQUIPE FOREIGN KEY (NomEquipe) REFERENCES Equipe(NomEquipe),"
				+ "CONSTRAINT PK_IDJOUEUR PRIMARY KEY (IdJoueur))");
		// Table Arbitres
		statement.executeUpdate("create table Arbitres( IdArbitres int GENERATED BY DEFAULT AS IDENTITY,"
				+ " Nom Varchar(20)," + "Prenom Varchar(20)," + " constraint PK_IDARBITRES PRIMARY KEY (IdArbitres))");
		// Table Saison
		statement.executeUpdate("create table Saison(Annee char(4), constraint PK_ANNEE PRIMARY KEY (Annee))");

		// Table Tournoi
		statement.executeUpdate("create table Tournoi( IdTournoi int GENERATED BY DEFAULT AS IDENTITY, Nom Varchar(20),"
				+ " Ligue Varchar(20), DateDebut Varchar(10), DateFin Varchar(10), Login Varchar(20), "
				+ " MotDePasse Varchar(50), " + " Annee char(4), " + "constraint PK_IDTOURNOI PRIMARY KEY (IdTournoi), "
				+ "constraint FK_SAISON_ANNEE FOREIGN KEY (Annee) REFERENCES Saison(Annee))");
		// Table Arbitrer
		statement.executeUpdate("CREATE TABLE Arbitrer (IdTournoi INT, IdArbitres INT,"
				+ "constraint FK_ARBITRER_IDTOURNOI FOREIGN KEY (IdTournoi) REFERENCES Tournoi(IdTournoi),"
				+ "constraint FK_ARBITRER_IDARBITRES FOREIGN KEY (IdArbitres) REFERENCES Arbitres(IdArbitres),"
				+ "constraint PK_IDARBITRES_IDTOURNOI PRIMARY KEY (IdTournoi, IdArbitres))");
		// Table Matchs
		statement.executeUpdate("CREATE TABLE Matchs(" + "IdMatchs INT, " + "IdTournoi INT, "
				+ "NomEquipe varchar(50), " + "NbPoints INT, "
				+ "CONSTRAINT FK_MATCHS_IDEQUIPE FOREIGN KEY (NomEquipe) REFERENCES Equipe(NomEquipe), "
				+ "CONSTRAINT FK_MATCHS_IDTOURNOI FOREIGN KEY (IdTournoi) REFERENCES Tournoi(IdTournoi), "
				+ "CONSTRAINT PK_IDTOURNOI_IDEQUIPE_IDMATCHS PRIMARY KEY (IdTournoi, NomEquipe, IdMatchs))");

		// Table participer
		statement.executeUpdate("create table Participer(" + "NomEquipe varchar(50), " + "Annee char(4), "
				+ "constraint FK_PARTICIPER_NOMEQUIPE FOREIGN KEY (NomEquipe) REFERENCES Equipe(NomEquipe), "
				+ "constraint FK_PARTICIPER_ANNEE FOREIGN KEY (Annee) REFERENCES Saison(Annee), "
				+ "constraint PK_IDEQUIPE_ANNEE PRIMARY KEY (NomEquipe,Annee))");

		statement.executeUpdate("insert into Administrateur (Login, MotDePasse) VALUES ('admin', 'admin')");
		statement.executeUpdate("insert into Saison VALUES ('2019')");
		statement.executeUpdate("insert into Saison VALUES ('2020')");
		statement.executeUpdate("insert into Saison VALUES ('2021')");
		statement.executeUpdate("insert into Saison VALUES ('2022')");
		statement.executeUpdate("insert into Saison VALUES ('2023')");
		statement.executeUpdate("insert into Saison VALUES ('2024')");

		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('Equipe6', 'France')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('Team du sud', 'France')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('Karmine Corp', 'France')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('Gentle Mates', 'France')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('Fnatic', 'Angleterre')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('G2 Esports', 'Allemagne')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('GIANTX', 'Allemagne')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays) VALUES ('SK Gaming', 'Allemagne')");
		statement.executeUpdate("INSERT INTO Equipe (NomEquipe, Pays)" + " VALUES ('Vitality', 'France'),"
				+ "	('Team GO', 'Taiwan')," + " ('Taipei Bravo', 'Taiwan')," + "	('PSG Academy', 'Taiwan')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES " + "('Czajek', 'Vitality'),"
				+ "('Naak Nako', 'Vitality')," + "('Selfmade', 'Vitality')," + "('Jopa', 'Vitality'),"
				+ "('Stend', 'Vitality')," + "('Six10', 'Team GO')," + "('Prime', 'Team GO')," + "('Lot', 'Team GO'),"
				+ "('Boukada', 'Team GO')," + "('Jezu', 'Team GO')," + "('pinwei', 'Taipei Bravo'),"
				+ "('Mob', 'Taipei Bravo')," + "('ZhifeiG', 'Taipei Bravo')," + "('Yuuto', 'Taipei Bravo'),"
				+ "('Cause', 'Taipei Bravo')," + "('Wen', 'PSG Academy')," + "('TNS', 'PSG Academy'),"
				+ "('Chich1', 'PSG Academy')," + "('mikey', 'PSG Academy')," + "('Adizai', 'PSG Academy')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Cléclé', 'Equipe6')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Vivi', 'Equipe6')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Mateo', 'Equipe6')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Christopher', 'Equipe6')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('MaxLaMenace', 'Equipe6')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Booshi', 'Team du sud')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Coldraa', 'Team du sud')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('FEBIVEN', 'Team du sud')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('SLT', 'Team du sud')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('TynX', 'Team du sud')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Cabochard', 'Karmine Corp')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Bo', 'Karmine Corp')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('SAKEN', 'Karmine Corp')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Upset', 'Karmine Corp')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Targamas', 'Karmine Corp')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('BAO', 'Gentle Mates')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Ragner', 'Gentle Mates')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('kamilius', 'Gentle Mates')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('White', 'Gentle Mates')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Eika', 'Gentle Mates')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Noah', 'Fnatic')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Jun', 'Fnatic')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Oscarinin', 'Fnatic')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Humanoid', 'Fnatic')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Razork', 'Fnatic')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Caps', 'G2 Esports')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('BrokenBlade', 'G2 Esports')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Yike', 'G2 Esports')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Hans Sama', 'G2 Esports')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Mikyx', 'G2 Esports')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Peach', 'GIANTX')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Patrik', 'GIANTX')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Odoamne', 'GIANTX')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Jackies', 'GIANTX')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('IgNar', 'GIANTX')");

		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Bertho', 'SK Gaming')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('ISMA', 'SK Gaming')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Nisqy', 'SK Gaming')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Irrelevant', 'SK Gaming')");
		statement.executeUpdate("INSERT INTO Joueur (Pseudo, NomEquipe) VALUES ('Exakick', 'SK Gaming')");

		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Fnatic', '2019')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('G2 Esports', '2019')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('SK Gaming', '2019')");

		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Fnatic', '2020')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('G2 Esports', '2020')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('SK Gaming', '2020')");

		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Equipe6', '2022')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Team du sud', '2022')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Karmine Corp', '2022')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Fnatic', '2022')");

		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Equipe6', '2023')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Team du sud', '2023')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Karmine Corp', '2023')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Fnatic', '2023')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('G2 Esports', '2023')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('GIANTX', '2023')");

		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Equipe6', '2024')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Team du sud', '2024')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Karmine Corp', '2024')");
		statement.executeUpdate("INSERT INTO Participer (NomEquipe, Annee) VALUES ('Gentle Mates', '2024')");

		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiA', 'LOCAL', '12-12-2024', '13-12-2024', 'tournoiA', 'admin', '2024')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiB', 'LOCAL', '20-12-2023', '22-12-2023', 'admin', 'admin', '2023')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiC', 'NATIONAL', '23-12-2023', '24-12-2023', 'admin', 'admin', '2023')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiD', 'REGIONAL', '25-12-2023', '26-12-2023', 'tournoiD', 'mdpTD', '2023')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiF', 'INTERNATIONAL_CLASSE', '30-12-2023', '31-12-2023', 'admin', 'admin', '2023')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('PCL 2023', 'Local', '15-08-2023', '25-08-2023', 'admin', 'admin', '2023')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiG', 'NATIONAL', '20-12-2022', '22-12-2022', 'admin', 'admin', '2022')");
		statement.executeUpdate(
				"INSERT INTO Tournoi (Nom, Ligue, DateDebut, DateFin, Login, MotDePasse, Annee) VALUES ('TournoiH', 'NATIONAL', '23-12-2022', '24-12-2022', 'admin', 'admin', '2022')");

		statement.executeUpdate("INSERT INTO Arbitres (Nom, Prenom) VALUES ('Letaxi', 'Joe')");
		statement.executeUpdate("INSERT INTO Arbitres(Nom, Prenom) VALUES ('Bagarre', 'Joe')");
		statement.executeUpdate("INSERT INTO Arbitres (Nom, Prenom) VALUES ('Raoult', 'Didier')");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (0,1, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (0,1, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (1,1, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (1,1, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (2,1, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (2,1, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (3,1, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (3,1, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (4,1, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (4,1, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (5,1, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (5,1, 'Gentle Mates', 1)");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (1,2, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (1,2, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (2,2, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (2,2, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (3,2, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (3,2, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (4,2, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (4,2, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (5,2, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (5,2, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (6,2, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (6,2, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (13,2, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (13,2, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (7,2, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (7,2, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (8,2, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (8,2, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (9,2, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (9,2, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (14,2, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (14,2, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (10,2, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (10,2, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (11,2, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (11,2, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (12,2, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (12,2, 'Taipei Bravo', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (15,2, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (15,2, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (16,2, 'PSG Academy', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs,IdTournoi, NomEquipe, NbPoints) VALUES (16,2, 'Taipei Bravo', 3)");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 3, 'Vitality', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 3, 'Team GO', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 3, 'Vitality', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 3, 'Fnatic', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 3, 'Vitality', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 3, 'G2 Esports', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 3, 'Team GO', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 3, 'Fnatic', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 3, 'Team GO', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 3, 'G2 Esports', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 3, 'Fnatic', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 3, 'G2 Esports', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 3, 'GIANTX', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 3, 'Vitality', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 3, 'GIANTX', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 3, 'Team GO', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 3, 'GIANTX', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 3, 'Fnatic', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 3, 'GIANTX', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 3, 'G2 Esports', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (12, 3, 'Team GO', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (12, 3, 'GIANTX', 1)");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 4, 'Taipei Bravo', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 4, 'Gentle Mates', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 4, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 4, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 4, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 4, 'PSG Academy', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 4, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 4, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 4, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 4, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 4, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 4, 'Taipei Bravo', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 4, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 4, 'Taipei Bravo', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 4, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 4, 'Gentle Mates', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 4, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 4, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 4, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 4, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (11, 4, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (11, 4, 'Gentle Mates', 1)");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 7, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 7, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 7, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 7, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 7, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 7, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 7, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 7, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 7, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 7, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 7, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 7, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 7, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 7, 'Team du sud', 1)");

		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 8, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 8, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 8, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 8, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 8, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 8, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 8, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 8, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 8, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 8, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 8, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 8, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 8, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 8, 'Team du sud', 3)");

		// Premier ensemble de matchs
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 5, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 5, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 5, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 5, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 5, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 5, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 5, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 5, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 5, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 5, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 5, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 5, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (13, 5, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (13, 5, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 5, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 5, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 5, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (8, 5, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 5, 'Taipei Bravo', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (9, 5, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (14, 5, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (14, 5, 'Equipe6', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 5, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (10, 5, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (11, 5, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (11, 5, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (12, 5, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (12, 5, 'Taipei Bravo', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (15, 5, 'PSG Academy', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (15, 5, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (16, 5, 'PSG Academy', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (16, 5, 'Taipei Bravo', 3)");

		// Premier ensemble de matchs
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 6, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (1, 6, 'Team du sud', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 6, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (2, 6, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 6, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (3, 6, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 6, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (4, 6, 'Karmine Corp', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 6, 'Team du sud', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (5, 6, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 6, 'Karmine Corp', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (6, 6, 'Gentle Mates', 1)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 6, 'Equipe6', 3)");
		statement.executeUpdate(
				"INSERT INTO Matchs (IdMatchs, IdTournoi, NomEquipe, NbPoints) VALUES (7, 6, 'Team du sud', 1)");

		c.commit();
		System.out.println("Base de données créée avec succès");
		
	}
}
